version: "3.9"
services:
  qtest_ser_qif_pgback:
    tty: true
    stdin_open: true
    container_name: qtest_con_qif_pgback
    image: pointeldevs/run_data
    volumes:
      - ${QIN_ROOT}/Work:/root
      - ${QIN_ROOT}/Code:/root/Code
      - ${QIF_PGBACK_DATA}:/root/pgbacked
    environment:
      - QIN_ROOT=/root
      - QIF_PGBACK_DATA=/root/pgbacked
      - QIF_PGBACK_ENTRY=${QIF_PGBACK_ENTRY}
    networks:
      - qin_net_stk
    working_dir: /root/Code/qif_pgback
    entrypoint: ./entry.sh

networks:
  qin_net_stk:
    external: true