version: "3.9"
services:
  qtest_ser_qir_pgback:
    tty: true
    stdin_open: true
    container_name: qtest_qir_pgback
    image: pointeldevs/run_data
    volumes:
      - ${QIN_ROOT}/Work:/root
      - ${QIN_ROOT}/Code:/root/Code
      - ${QIR_PGBACK_DATA}:/root/pgbacked
    environment:
      - QIN_ROOT=/root
      - QIR_PGBACK_DATA=/root/pgbacked
      - QIR_PGBACK_ENTRY=${QIR_PGBACK_ENTRY}
      - QIR_PGBACK_HOST=qvess_stk_postgres
    networks:
      - qin_net_stk
    working_dir: /root/Code/qir_pgback
    entrypoint: ./entry.sh

networks:
  qin_net_stk:
    external: true
