version: "3.9"
services:
  qcode_ser_qir_pgback:
    tty: true
    stdin_open: true
    container_name: qcode_con_qir_pgback
    image: pointeldevs/run_data
    volumes:
      - ${QIN_ROOT}/Work:/root
      - ${QIN_ROOT}/Code:/root/Code
      - ${QIR_PGBACK_DATA}:/root/pgbacked
    environment:
      - QIN_ROOT=/root
      - QIR_PGBACK_DATA=/root/pgbacked
    networks:
      - qin_net_stk
    working_dir: /root/Code/qir_pgback

networks:
  qin_net_stk:
    external: true
