version: "3.9"
services:
  qprod_ser_qir_pgback:
    tty: true
    stdin_open: true
    container_name: qprod_con_qir_pgback
    image: pointeldevs/run_data
    volumes:
      - ${QIN_ROOT}/Work:/root
      - ${QIN_ROOT}/Code:/root/Code
      - ${QIR_PGBACK_DATA}:/root/pgbacked
    environment:
      - QIN_ROOT=/root
      - QIR_PGBACK_DATA=/root/pgbacked
      - QIR_PGBACK_ENTRY=${QIR_PGBACK_ENTRY}
      - QIR_PGBACK_HOST=qcon_run_postgres
    restart: always
    networks:
      - qin_net_run
    working_dir: /root/Code/qir_pgback
    entrypoint: ./entry.sh

networks:
  qin_net_run:
    external: true
